### ISSUE TITLE
Questions - no response when emailing..

### ISSUE THREAD

**Issue by PCAssistSoftware** [Excepticon/excepticon-dotnet#1]
As getting no response to emails sent I thought I would try asking here instead:-

Firstly just for info - dead link on https://docs.excepticon.io/ the link to            “Client Libraries” is dead    - missing an r in libraries 😊

And now on to the questions I asked via email on 29/10

Firstly I would like to say I have spent ages researching and testing some of the other available solutions, and was so glad to find your product specifically aimed at indie developers like myself, as you say a lot of the other products available are so bulky with unneeded areas and always seem to be aimed at teams of 5 at a minimum

1)	I have been testing the same exception using VB.NET with all products, and this particular exception as two inner exceptions – in your product this is not being shown in the stack trace etc – and is obviously a big issue

2)	More of an issue is that it seems to log error fine when I run app in debugger (Visual Studio), but NOT when I am running app standalone as it would normally run

3)	The NuGet package seems to add an amazing amount of extra DLL’s to my product – 26 in total – and quite a few of them seem to be related to AspNetCore which I am not even using.  Other products tested add one maybe two DLL’s – so this could do with being improved if possible?

4)	You really need some sort of email alert to be sent out when a new exception is logged

For info I am using your solution in a WinForms app using VB

**Comment by PCAssistSoftware** [comment]
12 days later - no response to any emails I sent or on here - so will assume project is dead

**Comment by jonblankenship** [comment]
Hello - my apologies for failing to respond in a timely manner.  Due to a lack of interest, there is no active development happening on this project.

**Comment by PCAssistSoftware** [comment]
To be fair I am not surprised a lack of interest when emails from 17 days ago go unanswered, doesn't exactly inspire confidence.  But thanks for at least finally letting me know I was wasting my time. Shame as the idea was good even if it has a lot of issues.
